// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-3')['BAlert']
    BButton: typeof import('bootstrap-vue-3')['BButton']
    BDropdownDivider: typeof import('bootstrap-vue-3')['BDropdownDivider']
    BDropdownItem: typeof import('bootstrap-vue-3')['BDropdownItem']
    BFormInput: typeof import('bootstrap-vue-3')['BFormInput']
    BNav: typeof import('bootstrap-vue-3')['BNav']
    BNavbar: typeof import('bootstrap-vue-3')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-3')['BNavbarBrand']
    BNavBrand: typeof import('bootstrap-vue-3')['BNavBrand']
    BNavItem: typeof import('bootstrap-vue-3')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-3')['BNavItemDropdown']
    BNavText: typeof import('bootstrap-vue-3')['BNavText']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NavBar: typeof import('./src/components/NavBarComponents/NavBar.vue')['default']
    NavElements: typeof import('./src/components/NavBarComponents/NavElements.vue')['default']
    NavElementsDashboard: typeof import('./src/components/NavBarComponents/NavElementsDashboard.vue')['default']
    NavOptionsDashboard: typeof import('./src/components/NavBarComponents/NavOptionsDashboard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
